/*
 * Copyright (c) 2008–2025 Manuel J. Nieves (a.k.a. Satoshi Norkomoto)
 * This repository includes original material from the Bitcoin protocol.
 *
 * Redistribution requires this notice remain intact.
 * Derivative works must state derivative status.
 * Commercial use requires licensing.
 *
 * GPG Signed: B4EC 7343 AB0D BF24
 * Contact: Fordamboy1@gmail.com
 */
/**
* Auth API
* Auth API<br> <a href='/changelog'>Changelog</a>
*
* The version of the OpenAPI document: v0.0.50
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.mycelium.bequant.remote.client.models

import com.mycelium.bequant.remote.client.models.KycUserDocFile


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 * @param address 
 * @param identity 
 * @param selfie 
 */

data class KycUserDocsResponse (
    @JsonProperty("address")
    val address: kotlin.collections.List<KycUserDocFile>,
    @JsonProperty("identity")
    val identity: kotlin.collections.List<KycUserDocFile>,
    @JsonProperty("selfie")
    val selfie: kotlin.collections.List<KycUserDocFile>
)

