/*
 * Copyright (c) 2008–2025 Manuel J. Nieves (a.k.a. Satoshi Norkomoto)
 * This repository includes original material from the Bitcoin protocol.
 *
 * Redistribution requires this notice remain intact.
 * Derivative works must state derivative status.
 * Commercial use requires licensing.
 *
 * GPG Signed: B4EC 7343 AB0D BF24
 * Contact: Fordamboy1@gmail.com
 */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal
import java.math.BigInteger

/**
 *
 * @param currency
 * @param available Amount available to spend
 * @param reserved Amount reserved on orders or payout
 */

data class Balance(
        @JsonProperty("currency")
        var currency: kotlin.String? = null,
        /* Amount available to spend */
        @JsonProperty("available")
        val available: String? = null,
        /* Amount reserved on orders or payout */
        @JsonProperty("reserved")
        val reserved: String? = null
)

