/*
 * Copyright (c) 2008–2025 Manuel J. Nieves (a.k.a. Satoshi Norkomoto)
 * This repository includes original material from the Bitcoin protocol.
 *
 * Redistribution requires this notice remain intact.
 * Derivative works must state derivative status.
 * Commercial use requires licensing.
 *
 * GPG Signed: B4EC 7343 AB0D BF24
 * Contact: Fordamboy1@gmail.com
 */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret as password to authorize.
 *
 * The version of the OpenAPI document: 2.19.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mycelium.bequant.remote.trading.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 * @param id
 * @param price
 * @param quantity
 * @param side
 * @param timestamp
 */

data class PublicTrade(
        @JsonProperty("id")
        val id: kotlin.Int? = null,
        @JsonProperty("price")
        val price: kotlin.String? = null,
        @JsonProperty("quantity")
        val quantity: kotlin.String? = null,
        @JsonProperty("side")
        val side: PublicTrade.Side? = null,
        @JsonProperty("timestamp")
        val timestamp: java.util.Date? = null
) {

    /**
     *
     * Values: sell,buy
     */

    enum class Side(val value: kotlin.String) {
        @JsonProperty("sell")
        sell("sell"),
        @JsonProperty("buy")
        buy("buy");
    }
}

