name: CI
on:
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master
jobs:
  build:
    if: >
      !contains(github.event.head_commit.message, '#skip-ci')
    runs-on: ubuntu-latest
    steps:

    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: cmdline-tools;latest

    - name: Install deps
      run: sudo apt-get install -y unzip diffutils

    - name: Set up JDK environment
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - run: ./gradlew clean test mbw::assembleProdnetDebug mbw::assembleBtctestnetDebug

    - uses: actions/upload-artifact@v3
      with:
        path: mbw/build/outputs/apk/

    - name: Check Target SDK
      run: |
        target_sdk=$(/usr/local/lib/android/sdk/cmdline-tools/latest/bin/apkanalyzer manifest target-sdk mbw/build/outputs/apk/prodnet/debug/mbw-prodnet-debug.apk)
        echo "$target_sdk" | grep "^31$"

    - run: mv mbw/build/outputs/apk /tmp/buildA

    - name: Reproduce build
      run: |
        git reset --hard HEAD
        git clean -dfx
        rm -rf fiosdk_kotlin/androidfioserializationprovider/.cxx/        
        ./gradlew clean mbw::assembleProdnetDebug

    - name: Unzip buildA
      run: unzip -d buildA -qq /tmp/buildA/prodnet/debug/mbw-prodnet-debug.apk

    - name: Unzip buildB
      run: unzip -d buildB -qq mbw/build/outputs/apk/prodnet/debug/mbw-prodnet-debug.apk

    - name: Compare builds
      run: |
        set -x;
        diffResult=$( diff --brief --recursive buildA buildB ) && diffExactlyTheSame=true;
        diffCount=$( echo "$diffResult" | grep -vcE "(META-INF|^$)" ) && diffSignificant=true;
        if ((diffCount != 0)); then
          exit 1;
        fi
