name: RC
on:
  push:
    branches: [master, ci-build-rc]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    if: >
      !contains(github.event.head_commit.message, '#skip-ci')
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: docker/build-push-action@v4
      with:
        tags: mycelium_builder:latest
        push: false
        context: ${{ github.workspace }}

    - uses: addnab/docker-run-action@v3
      with:
        image: mycelium_builder:latest
        options: >
          --volume ${{ github.workspace }}:/project/
        run: |
          cd /project/
          ./gradlew clean test mbw::assembleProdnetRelease mbw::assembleBtctestnetRelease mbw::assembleProdnetDebug mbw::assembleBtctestnetDebug

    - uses: actions/upload-artifact@v3
      with:
        path: mbw/build/outputs/
